export type OvertimeRequestItem = {
    id: number;
    record_number: string;
    employee_id: number;
    employee: {
        id: number;
        name: string;
        staff_id: string;
        department: { id: number; name: string } | null;
    } | null;
    overtime_date: string;
    start_time: string | null;
    end_time: string | null;
    hours: number;
    reason: string;
    status: string;
    status_label: string;
    status_color: string;
    approver_employee_id: number | null;
    approver: { id: number; name: string; staff_id: string } | null;
    approver_label: string | null;
    approval_steps?: Array<{
        id: number;
        step_order: number;
        step_key: string;
        label: string;
        status: string;
        status_label: string;
        status_color: string;
        approver: { id: number; name: string; staff_id: string } | null;
        acted_by: { id: number; name: string; staff_id: string } | null;
        acted_at: string | null;
        notes: string | null;
    }>;
    manager_reviewed_by_employee_id: number | null;
    manager_reviewed_by: { id: number; name: string; staff_id: string } | null;
    manager_reviewed_at: string | null;
    manager_review_notes: string | null;
    reviewed_by_employee_id: number | null;
    reviewed_by: { id: number; name: string; staff_id: string } | null;
    reviewed_at: string | null;
    review_notes: string | null;
    created_at: string | null;
};
